from __future__ import annotations

from decimal import Decimal
from pathlib import Path
from typing import Optional

import json

from django.conf import settings

from .models import ValuationSettings


_LINEAR_MODEL_CACHE: Optional[dict] = None


def _load_linear_model_payload() -> Optional[dict]:
    """
    Load linear $/WAR by position payload generated by
    scripts/estimate_position_dollars_per_war.py.

    The script writes JSON to data/position_dollars_per_war_model.json with:
    {
      "base_WAR_coef": ...,
      "positions": {
        "C": {"dollars_per_WAR": ..., ...},
        ...
      },
      "n_obs": ...,
      "year_min": ...,
      "year_max": ...
    }
    """
    global _LINEAR_MODEL_CACHE
    if _LINEAR_MODEL_CACHE is not None:
        return _LINEAR_MODEL_CACHE

    path = Path(settings.BASE_DIR) / "data" / "position_dollars_per_war_model.json"
    if not path.exists():
        return None
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None
    _LINEAR_MODEL_CACHE = payload
    return payload


def get_dollars_per_war(position: str, age: Optional[int], year: Optional[int], war: float) -> Optional[Decimal]:
    """
    Return the marginal $/WAR for the given position under the currently
    selected valuation method.

    Parameters
    ----------
    position:
        Position code (e.g. 'C', '1B', 'SP').
    age:
        Optional age at signing; currently ignored by the linear engine but
        included for future ML-based pricing.
    year:
        Optional signing year; currently ignored by the linear engine but can
        be used when the ML engine is implemented.
    war:
        WAR level around which to evaluate the marginal value; currently only
        used by the ML engine.

    Returns
    -------
    Decimal or None
        Estimated marginal dollars per WAR, or None if no estimate is
        available for the given position / settings.
    """
    settings_obj = ValuationSettings.get_solo()
    method = settings_obj.valuation_method

    if method == ValuationSettings.VALUATION_METHOD_LINEAR:
        payload = _load_linear_model_payload()
        if not payload:
            return None
        pos_info = payload.get("positions", {}).get(position)
        if not pos_info:
            return None
        return Decimal(str(pos_info.get("dollars_per_WAR")))

    if method == ValuationSettings.VALUATION_METHOD_ML:
        # Placeholder: to be implemented when an ML/DL pricing model is trained.
        # For now, fall back to linear if available.
        payload = _load_linear_model_payload()
        if not payload:
            return None
        pos_info = payload.get("positions", {}).get(position)
        if not pos_info:
            return None
        return Decimal(str(pos_info.get("dollars_per_WAR")))

    return None

