# Generated by Django 5.2.5 on 2026-03-10 12:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLBPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(blank=True, choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('1B', 'First Base'), ('2B', 'Second Base'), ('3B', 'Third Base'), ('SS', 'Shortstop'), ('LF', 'Left Field'), ('CF', 'Center Field'), ('RF', 'Right Field'), ('DH', 'Designated Hitter')], max_length=10)),
                ('photo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'MLB Player',
                'verbose_name_plural': 'MLB Players',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MLBPlayerPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_value', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Predicted market value (MRP)', max_digits=15)),
                ('next_year_avg', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('next_year_hr', models.PositiveIntegerField(blank=True, null=True)),
                ('next_year_ops', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('next_year_era', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='mlb.mlbplayer')),
            ],
            options={
                'verbose_name': 'MLB Player Prediction',
                'verbose_name_plural': 'MLB Player Predictions',
            },
        ),
        migrations.CreateModel(
            name='MLBPlayerSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('team', models.CharField(blank=True, max_length=50)),
                ('ab', models.PositiveIntegerField(default=0)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('hr', models.PositiveIntegerField(default=0)),
                ('rbi', models.PositiveIntegerField(default=0)),
                ('avg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=4)),
                ('obp', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=4)),
                ('slg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=4)),
                ('ops', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=5)),
                ('ip', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('era', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('so', models.PositiveIntegerField(default=0)),
                ('bb', models.PositiveIntegerField(default=0)),
                ('whip', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='mlb.mlbplayer')),
            ],
            options={
                'verbose_name': 'MLB Player Season',
                'verbose_name_plural': 'MLB Player Seasons',
                'ordering': ['-year'],
                'unique_together': {('player', 'year')},
            },
        ),
        migrations.CreateModel(
            name='MLBSimilarPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='0-1, higher = more similar', max_digits=5)),
                ('rank', models.PositiveIntegerField(default=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_from', to='mlb.mlbplayer')),
                ('similar_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='mlb.mlbplayer')),
            ],
            options={
                'verbose_name': 'MLB Similar Player',
                'verbose_name_plural': 'MLB Similar Players',
                'ordering': ['player', 'rank'],
                'unique_together': {('player', 'similar_player')},
            },
        ),
    ]
