# Generated by Django 5.2.5 on 2026-03-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlbplayerprediction',
            name='next_year_fip',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mlbplayerprediction',
            name='next_year_war',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='mlbplayerprediction',
            name='next_year_woba',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='mlbplayerprediction',
            name='next_year_wrc_plus',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlbplayerseason',
            name='babip',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Batting Average on Balls in Play', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='mlbplayerseason',
            name='bb_per_9',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Walks per 9 IP', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='mlbplayerseason',
            name='fip',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fielding Independent Pitching', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mlbplayerseason',
            name='k_per_9',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Strikeouts per 9 IP', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='mlbplayerseason',
            name='ops_plus',
            field=models.PositiveIntegerField(blank=True, help_text='OPS+ (100 = league average)', null=True),
        ),
        migrations.AddField(
            model_name='mlbplayerseason',
            name='war',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wins Above Replacement', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='mlbplayerseason',
            name='woba',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Weighted On-Base Average', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='mlbplayerseason',
            name='wrc_plus',
            field=models.PositiveIntegerField(blank=True, help_text='wRC+ (100 = league average)', null=True),
        ),
        migrations.AddField(
            model_name='mlbplayerseason',
            name='xfip',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected FIP', max_digits=5, null=True),
        ),
    ]
