# Generated by Django 5.2.5 on 2026-03-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0002_mlbplayerprediction_next_year_fip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('valuation_method', models.CharField(choices=[('linear', 'Linear regression (recommended)'), ('ml', 'Nonlinear ML/DL (experimental)')], default='linear', max_length=16)),
            ],
            options={
                'verbose_name': 'Valuation Settings',
                'verbose_name_plural': 'Valuation Settings',
            },
        ),
    ]
