# Generated by Django 5.2.5 on 2026-03-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0004_mlbapistatline'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLBRosterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField(db_index=True)),
                ('team_id', models.PositiveIntegerField(db_index=True)),
                ('team_name', models.CharField(max_length=100)),
                ('team_abbreviation', models.CharField(db_index=True, max_length=10)),
                ('league_name', models.CharField(blank=True, max_length=100)),
                ('division_name', models.CharField(blank=True, max_length=100)),
                ('player_id', models.PositiveIntegerField(db_index=True)),
                ('player_name', models.CharField(max_length=100)),
                ('player_link', models.CharField(blank=True, max_length=100)),
                ('jersey_number', models.CharField(blank=True, max_length=10)),
                ('position_code', models.CharField(blank=True, max_length=10)),
                ('position_name', models.CharField(blank=True, max_length=50)),
                ('position_type', models.CharField(blank=True, max_length=50)),
                ('position_abbreviation', models.CharField(blank=True, max_length=10)),
                ('status_code', models.CharField(blank=True, max_length=10)),
                ('status_description', models.CharField(blank=True, max_length=50)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MLB Roster Entry',
                'verbose_name_plural': 'MLB Roster Entries',
                'ordering': ['-season', 'team_abbreviation', 'player_name'],
                'unique_together': {('season', 'team_id', 'player_id')},
            },
        ),
    ]
