# Generated by Django 5.2.5 on 2026-04-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0007_mlbrosterphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLBApiSimilarPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_view', models.CharField(choices=[('batting', 'Batting'), ('pitching', 'Pitching')], db_index=True, max_length=20)),
                ('source_player_name', models.CharField(max_length=100)),
                ('source_name_ascii', models.CharField(blank=True, db_index=True, max_length=100)),
                ('source_mlbam_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('source_external_player_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('similar_player_name', models.CharField(max_length=100)),
                ('similar_name_ascii', models.CharField(blank=True, db_index=True, max_length=100)),
                ('similar_mlbam_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('similar_external_player_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('similar_team', models.CharField(blank=True, max_length=10)),
                ('similarity_score', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MLB API Similar Player',
                'verbose_name_plural': 'MLB API Similar Players',
                'ordering': ['stat_view', 'source_player_name', 'rank'],
                'unique_together': {('stat_view', 'source_name_ascii', 'rank')},
            },
        ),
    ]
