# Generated by Django 5.2.5 on 2026-05-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0011_mlbapiperformancevalueprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLBApiTeamDollarPerWar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(db_index=True, max_length=10, unique=True)),
                ('avg_payroll_m_3yr', models.FloatField(blank=True, null=True)),
                ('avg_batting_war_3yr', models.FloatField(blank=True, null=True)),
                ('avg_pitching_war_3yr', models.FloatField(blank=True, null=True)),
                ('avg_team_war_3yr', models.FloatField(blank=True, null=True)),
                ('n_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('avg_team_war_3yr_safe', models.FloatField(blank=True, null=True)),
                ('dollar_per_war_millions', models.FloatField(blank=True, null=True)),
                ('dollar_per_war', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MLB API Team Dollar Per WAR',
                'verbose_name_plural': 'MLB API Team Dollars Per WAR',
                'ordering': ['-dollar_per_war_millions', 'team'],
            },
        ),
    ]
