# Generated by Django 5.2.5 on 2026-05-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0012_mlbapiteamdollarperwar'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLBApiWarNext3Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_view', models.CharField(choices=[('batting', 'Batting'), ('pitching', 'Pitching')], db_index=True, max_length=20)),
                ('player_name_key', models.CharField(db_index=True, max_length=120)),
                ('player_name', models.CharField(max_length=100)),
                ('name_ascii', models.CharField(blank=True, max_length=100)),
                ('season', models.PositiveIntegerField(db_index=True)),
                ('team', models.CharField(db_index=True, max_length=10)),
                ('actual_war_next3_avg', models.FloatField(blank=True, null=True)),
                ('pred_war_next3_avg', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MLB API WAR Next 3 Prediction',
                'verbose_name_plural': 'MLB API WAR Next 3 Predictions',
                'ordering': ['stat_view', '-season', 'team', 'player_name'],
                'unique_together': {('stat_view', 'season', 'player_name_key', 'team')},
            },
        ),
    ]
