# Generated by Django 5.2.5 on 2026-05-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0013_mlbapiwarnext3prediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLBApiFa2022Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_view', models.CharField(choices=[('batting', 'Batting'), ('pitching', 'Pitching')], db_index=True, max_length=20)),
                ('season', models.PositiveIntegerField(db_index=True)),
                ('player_name', models.CharField(max_length=100)),
                ('name_ascii', models.CharField(blank=True, db_index=True, max_length=100)),
                ('previous_team', models.CharField(db_index=True, max_length=10)),
                ('contract_team', models.CharField(blank=True, max_length=10)),
                ('position', models.CharField(blank=True, max_length=20)),
                ('is_re_signing', models.BooleanField(default=False)),
                ('predicted_war', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('actual_aav_millions', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('predicted_aav_millions', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('position_scarcity_level', models.CharField(blank=True, max_length=20)),
                ('position_scarcity_war_threshold', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('position_scarcity_comp_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_boras', models.BooleanField(default=False)),
                ('age', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('age_signal_level', models.CharField(blank=True, max_length=32)),
                ('age_signal_is_aging_risk', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MLB API FA 2022 Analysis',
                'verbose_name_plural': 'MLB API FA 2022 Analyses',
                'ordering': ['stat_view', 'previous_team', 'player_name'],
                'unique_together': {('season', 'stat_view', 'name_ascii', 'previous_team')},
            },
        ),
    ]
