# Generated by Django 5.2.5 on 2026-05-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0014_mlbapifa2022analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlbapifa2022analysis',
            name='m2_by_team',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlbapifa2022analysis',
            name='m2_contract_team_millions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='mlbapifa2022analysis',
            name='m2_max_millions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='mlbapifa2022analysis',
            name='m2_max_team',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='mlbapifa2022analysis',
            name='m2_min_millions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='mlbapifa2022analysis',
            name='m2_min_team',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='mlbapifa2022analysis',
            name='team_specificity_dollar_per_war',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mlbapifa2022analysis',
            name='team_specificity_level',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
