# Generated by Django 5.2.5 on 2026-03-10 11:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('released', 'Released')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value', models.DecimalField(decimal_places=2, help_text='Total contract amount', max_digits=15)),
                ('guaranteed_ratio', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Ratio of guaranteed salary to total (0-1, e.g. 0.8 = 80%)', max_digits=3)),
                ('years', models.PositiveIntegerField(help_text='Contract length in years')),
                ('start_year', models.PositiveIntegerField(blank=True, null=True)),
                ('player', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='roster.player')),
            ],
        ),
    ]
