# Generated by Django 5.2.5 on 2026-03-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='years_to_retirement',
            field=models.PositiveIntegerField(blank=True, help_text='Years left until expected retirement', null=True, verbose_name='Years to retirement'),
        ),
    ]
