# Generated by Django 5.2.5 on 2026-03-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_add_years_to_retirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('pending', '대기'), ('active', '활성'), ('released', '방출')], default='pending', max_length=20),
        ),
    ]
